using System.Text;
using Workshop.Validator.Model;

namespace Workshop.Validator.Index;

/// <summary>
/// The listing READMEs people see when they browse the repository: one per type folder, one
/// per game folder under game-data. All generated; the marker line says so.
/// </summary>
public static class ReadmeGenerator
{
    private const string Marker = "<!-- Generated by tools/Validator build-index; edits are overwritten. -->";

    public static void WriteAll(string root, string repo, IReadOnlyList<(Manifest Manifest, long Total, long Current)> entries)
    {
        foreach (var folder in Kinds.AllFolders)
        {
            var kind = Kinds.FromFolder(folder)!.Value;
            var typeDir = Path.Combine(root, folder);
            Directory.CreateDirectory(typeDir);
            var ofKind = entries.Where(e => e.Manifest.Kind == kind).ToList();
            File.WriteAllText(
                Path.Combine(typeDir, "README.md"),
                kind == ItemKind.GameCustomData ? GameDataListing(root, ofKind) : TypeListing(kind, ofKind));
        }
    }

    private static string TypeListing(ItemKind kind, List<(Manifest Manifest, long Total, long Current)> entries)
    {
        var sb = new StringBuilder();
        sb.AppendLine(Marker);
        sb.AppendLine($"# {Kinds.DisplayName(kind)}");
        sb.AppendLine();
        sb.AppendLine(Intro(kind));
        sb.AppendLine();
        if (entries.Count == 0)
        {
            sb.AppendLine("Nothing here yet. Be the first: see [how to share](../README.md#sharing-your-own).");
            return sb.ToString();
        }

        sb.AppendLine($"{entries.Count} item(s), most downloaded first.");
        sb.AppendLine();
        sb.AppendLine("| | Name | Author | Version | Downloads | Updated |");
        sb.AppendLine("|---|---|---|---|---:|---|");
        foreach (var (manifest, total, _) in entries.OrderByDescending(e => e.Total).ThenBy(e => e.Manifest.Name, StringComparer.OrdinalIgnoreCase))
        {
            var folder = manifest.Id.Split('/').Last();
            sb.AppendLine($"| {Thumbnail(folder, manifest)} | [{Escape(manifest.Name)}]({folder}/) | {Escape(manifest.Author)} | {manifest.Version} | {total} | {manifest.Updated} |");
        }

        return sb.ToString();
    }

    private static string GameDataListing(string root, List<(Manifest Manifest, long Total, long Current)> entries)
    {
        var sb = new StringBuilder();
        sb.AppendLine(Marker);
        sb.AppendLine("# Per-game custom data");
        sb.AppendLine();
        sb.AppendLine(Intro(ItemKind.GameCustomData));
        sb.AppendLine();

        var byGame = entries
            .GroupBy(e => e.Manifest.Id.Split('/')[1], StringComparer.Ordinal)
            .OrderBy(g => g.First().Manifest.Game?.Name ?? g.Key, StringComparer.OrdinalIgnoreCase)
            .ToList();

        if (byGame.Count == 0)
        {
            sb.AppendLine("Nothing here yet. Be the first: see [how to share](../README.md#sharing-your-own).");
            return sb.ToString();
        }

        sb.AppendLine($"{byGame.Count} game(s), {entries.Count} item(s).");
        sb.AppendLine();
        sb.AppendLine("| | Game | Platform | Items | Downloads |");
        sb.AppendLine("|---|---|---|---:|---:|");
        foreach (var group in byGame)
        {
            var first = group.First().Manifest;
            var gameName = first.Game?.Name ?? group.Key;
            // The game's image is the most downloaded item's that has one.
            var pictured = group
                .OrderByDescending(e => e.Total)
                .ThenBy(e => e.Manifest.Name, StringComparer.OrdinalIgnoreCase)
                .Select(e => e.Manifest)
                .FirstOrDefault(m => m.Cover is not null || m.Preview is not null);
            var thumbnail = pictured is null ? "" : Thumbnail($"{group.Key}/{pictured.Id.Split('/').Last()}", pictured);
            sb.AppendLine($"| {thumbnail} | [{Escape(gameName)}]({group.Key}/) | {Escape(first.Game?.Platform ?? "")} | {group.Count()} | {group.Sum(e => e.Total)} |");

            var gameDir = Path.Combine(root, "game-data", group.Key);
            Directory.CreateDirectory(gameDir);
            File.WriteAllText(Path.Combine(gameDir, "README.md"), GameListing(gameName, first.Game?.Platform, group.ToList()));
        }

        return sb.ToString();
    }

    private static string GameListing(string gameName, string? platform, List<(Manifest Manifest, long Total, long Current)> entries)
    {
        var sb = new StringBuilder();
        sb.AppendLine(Marker);
        sb.AppendLine($"# {gameName}");
        sb.AppendLine();
        if (!string.IsNullOrWhiteSpace(platform))
        {
            sb.AppendLine($"Platform: {platform}");
            sb.AppendLine();
        }

        sb.AppendLine("| | Name | Author | Version | Customizes | Downloads | Updated |");
        sb.AppendLine("|---|---|---|---|---|---:|---|");
        foreach (var (manifest, total, _) in entries.OrderByDescending(e => e.Total).ThenBy(e => e.Manifest.Name, StringComparer.OrdinalIgnoreCase))
        {
            var folder = manifest.Id.Split('/').Last();
            sb.AppendLine($"| {Thumbnail(folder, manifest)} | [{Escape(manifest.Name)}]({folder}/) | {Escape(manifest.Author)} | {manifest.Version} | {Summarize(manifest)} | {total} | {manifest.Updated} |");
        }

        return sb.ToString();
    }

    /// <summary>A short phrase from `contents`, for the game-data tables.</summary>
    private static string Summarize(Manifest manifest)
    {
        var parts = new List<string>();
        void Add(string key, string label)
        {
            var value = manifest.Contents[key];
            if (value is null)
            {
                return;
            }

            if (value.GetValueKind() == System.Text.Json.JsonValueKind.Number && value.GetValue<int>() > 0)
            {
                parts.Add($"{value.GetValue<int>()} {label}");
            }
            else if (value.GetValueKind() == System.Text.Json.JsonValueKind.True)
            {
                parts.Add(label);
            }
        }

        Add("achievementIcons", "icons");
        Add("customAchievements", "custom achievements");
        Add("categories", "categories");
        Add("capstones", "capstones");
        Add("achievementOverrides", "overrides");
        Add("notes", "notes");
        Add("achievementOrder", "order");
        return parts.Count == 0 ? "" : string.Join(", ", parts);
    }

    private static string Intro(ItemKind kind) => kind switch
    {
        ItemKind.Colors => "Color sets: rarity, completed-game and trophy colors, per-platform colors, and resource overrides. Install from the Workshop in Playnite, or download the `.pacolors` from the item's release and import it under Settings > Workshop > Bundles.",
        ItemKind.NotificationStyle => "Looks for the unlock notification: colors, layout, badges, backgrounds, and optionally a custom template. Install from the Workshop in Playnite, or download the `.panotif` from the item's release and import it under Settings > Notifications > Appearance.",
        ItemKind.ScreenshotFrame => "Looks for the screenshot frame drawn around unlock captures. Install from the Workshop in Playnite, or download the `.paframe` from the item's release and import it under Settings > Notifications > Appearance.",
        ItemKind.ShowcasePage => "Showcase page layouts: which widgets, where, and how their grids are set up. Install from the Workshop in Playnite, or download the `.pashowcase` and import it from the Showcase page menu.",
        ItemKind.UnlockSounds => "Sound sets for unlock notifications, one file per rarity tier. Install from the Workshop in Playnite, or download the `.pasounds` and import it under Settings > Notifications > Unlock sounds.",
        ItemKind.Bundle => "Bundles of colors, unlock sounds, notification style and screenshot frame, each part saved as a preset on install. Install from the Workshop in Playnite, or download the `.pabundle` and import it under Settings > Workshop > Bundles.",
        ItemKind.GameCustomData => "Per-game customizations: icon sets, categories, capstones, custom achievements, notes and ordering, one folder per game. Install from the Workshop in Playnite (which matches the game in your library), or download the `.pa` and import it from the game's Manage Achievements window.",
        _ => ""
    };

    /// <summary>
    /// A fixed-width image for a table cell: the cover when the item has one, else the preview,
    /// else nothing. <paramref name="itemFolder"/> is the item folder relative to the listing.
    /// </summary>
    private static string Thumbnail(string itemFolder, Manifest manifest)
    {
        var image = manifest.Cover ?? manifest.Preview;
        return image is null ? "" : $"<img src=\"{itemFolder}/{image}\" width=\"{ThumbnailWidth}\">";
    }

    private const int ThumbnailWidth = 120;

    private static string Escape(string text) => text.Replace("|", "\\|").Replace("\n", " ").Trim();
}
